package view;

import controllers.AppController;
import controllers.ServiceRequestController;
import controllers.TechnicianController;
import model.ServiceRequest;
import model.Technician;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class MainAppFrame extends JFrame {
    public MainAppFrame() {
        setTitle("FazConcertos");
        setSize(600, 400);
        setLocationRelativeTo(null);
        setContentPane(appPanel);

        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                onCancel();
            }
        });

        initTechnicianView();
        initServiceOrderView();
    }

    private void onCancel() {
        AppController.quit();
        dispose();
    }

    private void initTechnicianView() {
        addBtn.addActionListener(e -> TechnicianController.addTechnician());

        editBtn.addActionListener(e -> TechnicianController.editTechnician(technicianList.getSelectedValue()));

        removeBtn.addActionListener(e -> {
            Technician technician = technicianList.getSelectedValue();
            int confirm = JOptionPane.showConfirmDialog(null,
                    "Tem certeza que deseja apagar o cadastro do técnico '" + technician.getName() + "'?",
                    "Confirmar remoção",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (confirm == JOptionPane.YES_OPTION) {
                TechnicianController.removeTechnician(technician);
                resetTechnicianView();
            }
        });

        ActionListener searchListener = e -> technicianList.setListData(TechnicianController.filter(technicianSearch.getText()));
        technicianSearchBtn.addActionListener(searchListener);
        technicianSearch.addActionListener(searchListener);

        technicianList.addListSelectionListener(e -> {
            boolean isSelectionEmpty = technicianList.isSelectionEmpty();
            editBtn.setEnabled(!isSelectionEmpty);
            removeBtn.setEnabled(!isSelectionEmpty);
        });

        resetTechnicianView();
    }

    public void resetTechnicianView() {
        technicianList.setListData(TechnicianController.getAll());
    }

    private void initServiceOrderView() {
        createServiceRequestBtn.addActionListener(e -> ServiceRequestController.addServiceRequest());

        viewServiceRequestBtn.addActionListener(e -> ServiceRequestController.editServiceRequest(serviceRequestList.getSelectedValue()));

        ActionListener searchListener = e -> serviceRequestList.setListData(ServiceRequestController.filter(serviceRequestSearch.getText()));
        technicianSearchBtn.addActionListener(searchListener);
        technicianSearch.addActionListener(searchListener);

        serviceRequestList.addListSelectionListener(e -> viewServiceRequestBtn.setEnabled(!serviceRequestList.isSelectionEmpty()));

        resetServiceOrderView();
    }

    public void resetServiceOrderView() {
        serviceRequestList.setListData(ServiceRequestController.getAll());
    }

    private JPanel appPanel;

    private JList<Technician> technicianList;
    private JButton addBtn;
    private JButton editBtn;
    private JButton removeBtn;
    private JTextField technicianSearch;

    private JButton technicianSearchBtn;
    private JList<ServiceRequest> serviceRequestList;
    private JButton createServiceRequestBtn;
    private JTextField serviceRequestSearch;
    private JButton serviceRequestSearchBtn;
    private JButton viewServiceRequestBtn;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        appPanel = new JPanel();
        appPanel.setLayout(new BorderLayout(0, 0));
        final JTabbedPane tabbedPane1 = new JTabbedPane();
        appPanel.add(tabbedPane1, BorderLayout.CENTER);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        panel1.setName("");
        panel1.setOpaque(true);
        tabbedPane1.addTab("Técnicos", panel1);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        panel1.add(panel2, BorderLayout.SOUTH);
        addBtn = new JButton();
        addBtn.setText("Adicionar");
        addBtn.setMnemonic('A');
        addBtn.setDisplayedMnemonicIndex(0);
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(addBtn, gbc);
        technicianSearch = new JTextField();
        technicianSearch.setMinimumSize(new Dimension(12, 26));
        technicianSearch.setOpaque(true);
        technicianSearch.setPreferredSize(new Dimension(12, 26));
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(technicianSearch, gbc);
        technicianSearchBtn = new JButton();
        technicianSearchBtn.setText("Buscar");
        technicianSearchBtn.setMnemonic('B');
        technicianSearchBtn.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(technicianSearchBtn, gbc);
        editBtn = new JButton();
        editBtn.setEnabled(false);
        editBtn.setText("Editar");
        editBtn.setMnemonic('E');
        editBtn.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(editBtn, gbc);
        removeBtn = new JButton();
        removeBtn.setEnabled(false);
        removeBtn.setText("Remover");
        removeBtn.setMnemonic('R');
        removeBtn.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(removeBtn, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, BorderLayout.CENTER);
        technicianList = new JList();
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        technicianList.setModel(defaultListModel1);
        technicianList.setSelectionMode(0);
        scrollPane1.setViewportView(technicianList);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        tabbedPane1.addTab("Ordens de serviço", panel3);
        final JScrollPane scrollPane2 = new JScrollPane();
        panel3.add(scrollPane2, BorderLayout.CENTER);
        serviceRequestList = new JList();
        final DefaultListModel defaultListModel2 = new DefaultListModel();
        serviceRequestList.setModel(defaultListModel2);
        serviceRequestList.setSelectionMode(0);
        scrollPane2.setViewportView(serviceRequestList);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        panel3.add(panel4, BorderLayout.SOUTH);
        createServiceRequestBtn = new JButton();
        createServiceRequestBtn.setText("Requisitar serviço");
        createServiceRequestBtn.setMnemonic('S');
        createServiceRequestBtn.setDisplayedMnemonicIndex(11);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        panel4.add(createServiceRequestBtn, gbc);
        serviceRequestSearchBtn = new JButton();
        serviceRequestSearchBtn.setText("Buscar");
        serviceRequestSearchBtn.setMnemonic('U');
        serviceRequestSearchBtn.setDisplayedMnemonicIndex(1);
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        panel4.add(serviceRequestSearchBtn, gbc);
        serviceRequestSearch = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(serviceRequestSearch, gbc);
        viewServiceRequestBtn = new JButton();
        viewServiceRequestBtn.setEnabled(false);
        viewServiceRequestBtn.setText("Detalhes");
        viewServiceRequestBtn.setMnemonic('D');
        viewServiceRequestBtn.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(viewServiceRequestBtn, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return appPanel;
    }
}
